### ISSUE TITLE
add anonymous tracking of execution

### ISSUE THREAD

**Issue by poldrack** [poldrack/myconnectome-vm#4]
send execution logs to s3://myconnectome-log without any identifying information about the user

**Comment by vsoch** [comment]
@poldrack mentioned testing this out, and if you want to send me whatever code you work with, I can work on implementing it. We can also use this PR to keep a list of variables to send.

**Comment by poldrack** [comment]
maybe use a hash on the mac address so that we can know when it's coming from the same machine?

**Comment by vsoch** [comment]
Let's do a quick sanity check that the VMs get assigned different addresses, look in this file:

`vim .vagrant.d/boxes/gridneuro/0/virtualbox/Vagrantfile`

```
  Vagrant::Config.run do |config|
  # This Vagrantfile is auto-generated by `vagrant package` to contain
  # the MAC address of the box. Custom configuration should be placed in
  # the actual `Vagrantfile` in this box.
 config.vm.base_mac = "080027880CA6"
 end
```
